/* config.h. Generated by cmake from config.h.cmake */

#ifndef TAGLIB_CONFIG_H
#define TAGLIB_CONFIG_H

/* Defined if your compiler supports some byte swap functions */
#cmakedefine   HAVE_GCC_BYTESWAP 1
#cmakedefine   HAVE_GLIBC_BYTESWAP 1
#cmakedefine   HAVE_MSC_BYTESWAP 1
#cmakedefine   HAVE_MAC_BYTESWAP 1
#cmakedefine   HAVE_OPENBSD_BYTESWAP 1

/* Defined if your compiler supports some atomic operations */
#cmakedefine   HAVE_GCC_ATOMIC 1
#cmakedefine   HAVE_MAC_ATOMIC 1
#cmakedefine   HAVE_WIN_ATOMIC 1
#cmakedefine   HAVE_IA64_ATOMIC 1

/* Defined if your compiler supports some safer version of vsprintf */
#cmakedefine   HAVE_VSNPRINTF 1
#cmakedefine   HAVE_VSPRINTF_S 1

/* Defined if your compiler supports ISO _strdup */
#cmakedefine   HAVE_ISO_STRDUP 1

/* Defined if zlib is installed */
#cmakedefine   HAVE_ZLIB 1

/* Indicates whether debug messages are shown even in release mode */
#cmakedefine   TRACE_IN_RELEASE 1

#cmakedefine TESTS_DIR "@TESTS_DIR@"

//JBH ==========================================================================<
/* Defined if an (external) app logger is to be used */
#cmakedefine   USE_APP_LOGGER 1
#cmakedefine   USE_QXTLOGGER 1
#cmakedefine   USE_JBHLOGGER 1

/* Defined for a general purpose build (not for AMS) */
#cmakedefine   JBH_BUILD_FOR_GENERAL 1

/* Defined if an embedded unicode encoder is to be used */
#cmakedefine   JBH_USE_EMBEDDED_UNICODE_ENCODER 1
//JBH ==========================================================================>

#endif
